#!/usr/bin/env python3
import os
import json
import sys

VERSION="ngs2counts-mock"

def run_ngs2counts():
    if len(sys.argv) > 1 and sys.argv[1] in ("-V", "--version"):
        print(VERSION)
        sys.exit(0)

    print("log")

    runfolder = sys.argv[1]

    outdir = os.path.join(runfolder, "ngs2counts")
    os.makedirs(outdir, exist_ok=True)

    if "--library-mapping" in sys.argv:
        for i in range(1, 9):
            fname = os.path.join(outdir, f"counts_{i}.csv")
            with open(fname, "w") as f:
                 f.write(f"mock library_mapping count file {i}\n")
    else:
        for i in range(1, 17):
            fname = os.path.join(outdir, f"counts_{i}.csv")
            with open(fname, "w") as f:
                f.write(f"mock count file {i}\n")

    if len(sys.argv) > 4:
        extra_args = " ".join(map(str, sys.argv[4:]))
        print("multiple additional arguments:", extra_args)

    metadata = {
        "version": "ngs2counts-mock"
    }

    with open(os.path.join(outdir, "run_metadata.json"), "w") as f:
        json.dump(metadata, f)

if __name__ == "__main__":
  run_ngs2counts()
